name: HealAndFeed
version: 2.0.0
main: Kylan1940\HealAndFeed\Main
api: 4.0.0
author: Kylan1940

commands:
  heal:
    description: "Added max player health"
    usage: /heal
  feed:
    description: "Restore hunger player and hunger saturation player"
    usage: /feed