# HEAL AND FEED CONFIGURATION
#
# HELP:
# \n for new line
# § for color and special symbols

# Config Version
# DON'T CHANGE THIS!!! 
config-version: "4" 

# Command:
no-permission-heal: "§cYou don't have §aHeal Command §cpermission"
no-permission-feed: "§cYou don't have §aFeed Command §cpermission"
no-permission-ui: "§cYou don't have §aHealAndFeed UI Command §cpermission"
console-command-heal: "§c/heal is heal for playerself and only in-game, for console you must /heal (playerOnline)"
console-command-feed: "§c/feed is feed for playerself and only in-game, for console you must /feed (playerOnline)"
console-command-ui: "§c/healfeed is only in-game"

# Message:
message-heal: "§aYou've been healed"
message-feed: "§aYou're full"
no-player-found: "§cThis player does not exist"

# UI
title: "§aHeal§7And§cFeed"
button-heal: "§aHeal"
button-feed: "§cFeed"